apiVersion: v1
kind: Pod
namespace: jenkins
metadata:
  labels:
    some-label: jenkins-slave
spec:
  containers:
  - name: slave-with-helm
    image: alpine/helm:2.14.0
    command:
    - cat
    tty: true
  - name: golang
    image: golang:1.14.2-alpine3.11
    command:
    - cat
    tty: true
  - name: docker
    image: docker:19.03
    command:
    - cat
    tty: true
