name: K8s check

on: [pull_request, issues]

jobs:
  deploy:
    name: Check the K8s Cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: get pods --all-namespaces | grep -v Running
